import type { CityData } from "./types";

/**
 * Database of 101 French préfectures (96 metropolitan + 5 overseas).
 * Each city links to its hospitals via slugs defined in hospitals-db.ts.
 * nearbyCities lists neighboring préfectures for internal linking.
 */
export const citiesDB: CityData[] = [
  // ─── Île-de-France ───────────────────────────────────────────
  { slug: "paris", name: "Paris", department: "Paris", departmentCode: "75", region: "Île-de-France", population: 2161000, postalCode: "75000", cpam: { name: "CPAM de Paris", phone: "36 46", address: "21 rue Georges Auric, 75019 Paris" }, hospitals: ["pitie-salpetriere", "hegp", "saint-louis", "lariboisiere", "cochin", "necker", "tenon", "bichat", "beaujon", "saint-antoine", "robert-debre", "armand-trousseau", "institut-curie-paris", "gustave-roussy"], nearbyCities: ["nanterre", "bobigny", "creteil", "evry-courcouronnes", "versailles", "pontoise", "melun"] },
  { slug: "nanterre", name: "Nanterre", department: "Hauts-de-Seine", departmentCode: "92", region: "Île-de-France", population: 96000, postalCode: "92000", cpam: { name: "CPAM des Hauts-de-Seine", phone: "36 46" }, hospitals: ["hopital-max-fourestier", "hopital-louis-mourier"], nearbyCities: ["paris", "bobigny", "versailles"] },
  { slug: "bobigny", name: "Bobigny", department: "Seine-Saint-Denis", departmentCode: "93", region: "Île-de-France", population: 54000, postalCode: "93000", cpam: { name: "CPAM de Seine-Saint-Denis", phone: "36 46" }, hospitals: ["hopital-avicenne", "hopital-jean-verdier"], nearbyCities: ["paris", "nanterre", "creteil"] },
  { slug: "creteil", name: "Créteil", department: "Val-de-Marne", departmentCode: "94", region: "Île-de-France", population: 92000, postalCode: "94000", cpam: { name: "CPAM du Val-de-Marne", phone: "36 46" }, hospitals: ["chu-henri-mondor", "hopital-intercommunal-creteil"], nearbyCities: ["paris", "bobigny", "evry-courcouronnes", "melun"] },
  { slug: "evry-courcouronnes", name: "Évry-Courcouronnes", department: "Essonne", departmentCode: "91", region: "Île-de-France", population: 69000, postalCode: "91000", cpam: { name: "CPAM de l'Essonne", phone: "36 46" }, hospitals: ["ch-sud-francilien"], nearbyCities: ["paris", "creteil", "versailles", "melun"] },
  { slug: "versailles", name: "Versailles", department: "Yvelines", departmentCode: "78", region: "Île-de-France", population: 85000, postalCode: "78000", cpam: { name: "CPAM des Yvelines", phone: "36 46" }, hospitals: ["ch-versailles"], nearbyCities: ["paris", "nanterre", "evry-courcouronnes", "chartres"] },
  { slug: "pontoise", name: "Pontoise", department: "Val-d'Oise", departmentCode: "95", region: "Île-de-France", population: 32000, postalCode: "95000", cpam: { name: "CPAM du Val-d'Oise", phone: "36 46" }, hospitals: ["ch-rene-dubos"], nearbyCities: ["paris", "beauvais", "nanterre"] },
  { slug: "melun", name: "Melun", department: "Seine-et-Marne", departmentCode: "77", region: "Île-de-France", population: 41000, postalCode: "77000", cpam: { name: "CPAM de Seine-et-Marne", phone: "36 46" }, hospitals: ["ch-melun"], nearbyCities: ["paris", "creteil", "evry-courcouronnes", "auxerre"] },

  // ─── Hauts-de-France ─────────────────────────────────────────
  { slug: "lille", name: "Lille", department: "Nord", departmentCode: "59", region: "Hauts-de-France", population: 236000, postalCode: "59000", cpam: { name: "CPAM du Nord", phone: "36 46" }, hospitals: ["chru-lille", "centre-oscar-lambret", "hopital-saint-vincent"], nearbyCities: ["arras", "laon", "amiens", "beauvais"] },
  { slug: "arras", name: "Arras", department: "Pas-de-Calais", departmentCode: "62", region: "Hauts-de-France", population: 41000, postalCode: "62000", cpam: { name: "CPAM du Pas-de-Calais", phone: "36 46" }, hospitals: ["ch-arras"], nearbyCities: ["lille", "amiens", "beauvais"] },
  { slug: "amiens", name: "Amiens", department: "Somme", departmentCode: "80", region: "Hauts-de-France", population: 134000, postalCode: "80000", cpam: { name: "CPAM de la Somme", phone: "36 46" }, hospitals: ["chu-amiens-picardie"], nearbyCities: ["beauvais", "arras", "lille", "rouen", "laon"] },
  { slug: "beauvais", name: "Beauvais", department: "Oise", departmentCode: "60", region: "Hauts-de-France", population: 56000, postalCode: "60000", cpam: { name: "CPAM de l'Oise", phone: "36 46" }, hospitals: ["ch-simone-veil-beauvais", "centre-dialyse-beauvais"], nearbyCities: ["amiens", "pontoise", "paris", "rouen"] },
  { slug: "laon", name: "Laon", department: "Aisne", departmentCode: "02", region: "Hauts-de-France", population: 25000, postalCode: "02000", cpam: { name: "CPAM de l'Aisne", phone: "36 46" }, hospitals: ["ch-laon"], nearbyCities: ["amiens", "reims", "lille", "charleville-mezieres"] },

  // ─── Grand Est ───────────────────────────────────────────────
  { slug: "strasbourg", name: "Strasbourg", department: "Bas-Rhin", departmentCode: "67", region: "Grand Est", population: 287000, postalCode: "67000", cpam: { name: "CPAM du Bas-Rhin", phone: "36 46" }, hospitals: ["chru-strasbourg", "centre-paul-strauss"], nearbyCities: ["colmar", "metz", "nancy"] },
  { slug: "colmar", name: "Colmar", department: "Haut-Rhin", departmentCode: "68", region: "Grand Est", population: 70000, postalCode: "68000", cpam: { name: "CPAM du Haut-Rhin", phone: "36 46" }, hospitals: ["ch-colmar"], nearbyCities: ["strasbourg", "besancon", "dijon"] },
  { slug: "metz", name: "Metz", department: "Moselle", departmentCode: "57", region: "Grand Est", population: 120000, postalCode: "57000", cpam: { name: "CPAM de la Moselle", phone: "36 46" }, hospitals: ["chr-metz-thionville"], nearbyCities: ["strasbourg", "nancy", "bar-le-duc", "charleville-mezieres"] },
  { slug: "nancy", name: "Nancy", department: "Meurthe-et-Moselle", departmentCode: "54", region: "Grand Est", population: 105000, postalCode: "54000", cpam: { name: "CPAM de Meurthe-et-Moselle", phone: "36 46" }, hospitals: ["chru-nancy", "centre-alexis-vautrin"], nearbyCities: ["metz", "strasbourg", "epinal", "bar-le-duc"] },
  { slug: "epinal", name: "Épinal", department: "Vosges", departmentCode: "88", region: "Grand Est", population: 32000, postalCode: "88000", cpam: { name: "CPAM des Vosges", phone: "36 46" }, hospitals: ["ch-epinal"], nearbyCities: ["nancy", "besancon", "colmar"] },
  { slug: "bar-le-duc", name: "Bar-le-Duc", department: "Meuse", departmentCode: "55", region: "Grand Est", population: 15000, postalCode: "55000", cpam: { name: "CPAM de la Meuse", phone: "36 46" }, hospitals: ["ch-bar-le-duc"], nearbyCities: ["nancy", "metz", "chalons-en-champagne"] },
  { slug: "chalons-en-champagne", name: "Châlons-en-Champagne", department: "Marne", departmentCode: "51", region: "Grand Est", population: 44000, postalCode: "51000", cpam: { name: "CPAM de la Marne", phone: "36 46" }, hospitals: ["ch-chalons-en-champagne"], nearbyCities: ["reims", "bar-le-duc", "troyes"] },
  { slug: "reims", name: "Reims", department: "Marne", departmentCode: "51", region: "Grand Est", population: 183000, postalCode: "51100", cpam: { name: "CPAM de la Marne", phone: "36 46" }, hospitals: ["chu-reims", "institut-jean-godinot"], nearbyCities: ["chalons-en-champagne", "laon", "charleville-mezieres"] },
  { slug: "troyes", name: "Troyes", department: "Aube", departmentCode: "10", region: "Grand Est", population: 61000, postalCode: "10000", cpam: { name: "CPAM de l'Aube", phone: "36 46" }, hospitals: ["ch-troyes"], nearbyCities: ["chalons-en-champagne", "auxerre", "dijon"] },
  { slug: "charleville-mezieres", name: "Charleville-Mézières", department: "Ardennes", departmentCode: "08", region: "Grand Est", population: 47000, postalCode: "08000", cpam: { name: "CPAM des Ardennes", phone: "36 46" }, hospitals: ["ch-charleville-mezieres"], nearbyCities: ["reims", "laon", "metz"] },
  { slug: "chaumont", name: "Chaumont", department: "Haute-Marne", departmentCode: "52", region: "Grand Est", population: 22000, postalCode: "52000", cpam: { name: "CPAM de la Haute-Marne", phone: "36 46" }, hospitals: ["ch-chaumont"], nearbyCities: ["troyes", "dijon", "epinal"] },

  // ─── Auvergne-Rhône-Alpes ────────────────────────────────────
  { slug: "lyon", name: "Lyon", department: "Rhône", departmentCode: "69", region: "Auvergne-Rhône-Alpes", population: 522000, postalCode: "69000", cpam: { name: "CPAM du Rhône", phone: "36 46" }, hospitals: ["hcl-lyon", "centre-leon-berard", "hopital-edouard-herriot", "hopital-femme-mere-enfant"], nearbyCities: ["saint-etienne", "bourg-en-bresse", "grenoble", "valence", "macon"] },
  { slug: "saint-etienne", name: "Saint-Étienne", department: "Loire", departmentCode: "42", region: "Auvergne-Rhône-Alpes", population: 174000, postalCode: "42000", cpam: { name: "CPAM de la Loire", phone: "36 46" }, hospitals: ["chu-saint-etienne"], nearbyCities: ["lyon", "clermont-ferrand", "le-puy-en-velay", "valence"] },
  { slug: "grenoble", name: "Grenoble", department: "Isère", departmentCode: "38", region: "Auvergne-Rhône-Alpes", population: 158000, postalCode: "38000", cpam: { name: "CPAM de l'Isère", phone: "36 46" }, hospitals: ["chu-grenoble-alpes"], nearbyCities: ["lyon", "chambery", "valence", "gap"] },
  { slug: "chambery", name: "Chambéry", department: "Savoie", departmentCode: "73", region: "Auvergne-Rhône-Alpes", population: 59000, postalCode: "73000", cpam: { name: "CPAM de la Savoie", phone: "36 46" }, hospitals: ["ch-chambery"], nearbyCities: ["grenoble", "annecy", "lyon"] },
  { slug: "annecy", name: "Annecy", department: "Haute-Savoie", departmentCode: "74", region: "Auvergne-Rhône-Alpes", population: 130000, postalCode: "74000", cpam: { name: "CPAM de la Haute-Savoie", phone: "36 46" }, hospitals: ["ch-annecy-genevois"], nearbyCities: ["chambery", "lyon", "bourg-en-bresse"] },
  { slug: "bourg-en-bresse", name: "Bourg-en-Bresse", department: "Ain", departmentCode: "01", region: "Auvergne-Rhône-Alpes", population: 42000, postalCode: "01000", cpam: { name: "CPAM de l'Ain", phone: "36 46" }, hospitals: ["ch-bourg-en-bresse"], nearbyCities: ["lyon", "macon", "annecy"] },
  { slug: "valence", name: "Valence", department: "Drôme", departmentCode: "26", region: "Auvergne-Rhône-Alpes", population: 65000, postalCode: "26000", cpam: { name: "CPAM de la Drôme", phone: "36 46" }, hospitals: ["ch-valence"], nearbyCities: ["grenoble", "lyon", "saint-etienne", "privas", "avignon"] },
  { slug: "privas", name: "Privas", department: "Ardèche", departmentCode: "07", region: "Auvergne-Rhône-Alpes", population: 8400, postalCode: "07000", cpam: { name: "CPAM de l'Ardèche", phone: "36 46" }, hospitals: ["ch-privas"], nearbyCities: ["valence", "le-puy-en-velay", "mende"] },
  { slug: "clermont-ferrand", name: "Clermont-Ferrand", department: "Puy-de-Dôme", departmentCode: "63", region: "Auvergne-Rhône-Alpes", population: 147000, postalCode: "63000", cpam: { name: "CPAM du Puy-de-Dôme", phone: "36 46" }, hospitals: ["chu-clermont-ferrand", "centre-jean-perrin"], nearbyCities: ["saint-etienne", "moulins", "le-puy-en-velay", "aurillac", "limoges", "tulle"] },
  { slug: "moulins", name: "Moulins", department: "Allier", departmentCode: "03", region: "Auvergne-Rhône-Alpes", population: 19000, postalCode: "03000", cpam: { name: "CPAM de l'Allier", phone: "36 46" }, hospitals: ["ch-moulins-yzeure"], nearbyCities: ["clermont-ferrand", "nevers", "bourges"] },
  { slug: "le-puy-en-velay", name: "Le Puy-en-Velay", department: "Haute-Loire", departmentCode: "43", region: "Auvergne-Rhône-Alpes", population: 19000, postalCode: "43000", cpam: { name: "CPAM de la Haute-Loire", phone: "36 46" }, hospitals: ["ch-le-puy"], nearbyCities: ["saint-etienne", "clermont-ferrand", "privas", "mende"] },
  { slug: "aurillac", name: "Aurillac", department: "Cantal", departmentCode: "15", region: "Auvergne-Rhône-Alpes", population: 25000, postalCode: "15000", cpam: { name: "CPAM du Cantal", phone: "36 46" }, hospitals: ["ch-aurillac"], nearbyCities: ["clermont-ferrand", "rodez", "tulle"] },

  // ─── Nouvelle-Aquitaine ──────────────────────────────────────
  { slug: "bordeaux", name: "Bordeaux", department: "Gironde", departmentCode: "33", region: "Nouvelle-Aquitaine", population: 260000, postalCode: "33000", cpam: { name: "CPAM de la Gironde", phone: "36 46" }, hospitals: ["chu-bordeaux", "institut-bergonie"], nearbyCities: ["agen", "mont-de-marsan", "perigueux", "angouleme", "la-rochelle"] },
  { slug: "limoges", name: "Limoges", department: "Haute-Vienne", departmentCode: "87", region: "Nouvelle-Aquitaine", population: 132000, postalCode: "87000", cpam: { name: "CPAM de la Haute-Vienne", phone: "36 46" }, hospitals: ["chu-limoges"], nearbyCities: ["gueret", "tulle", "angouleme", "poitiers", "clermont-ferrand"] },
  { slug: "poitiers", name: "Poitiers", department: "Vienne", departmentCode: "86", region: "Nouvelle-Aquitaine", population: 89000, postalCode: "86000", cpam: { name: "CPAM de la Vienne", phone: "36 46" }, hospitals: ["chu-poitiers"], nearbyCities: ["niort", "angouleme", "limoges", "tours", "la-rochelle"] },
  { slug: "niort", name: "Niort", department: "Deux-Sèvres", departmentCode: "79", region: "Nouvelle-Aquitaine", population: 59000, postalCode: "79000", cpam: { name: "CPAM des Deux-Sèvres", phone: "36 46" }, hospitals: ["ch-niort"], nearbyCities: ["poitiers", "la-rochelle", "angouleme"] },
  { slug: "la-rochelle", name: "La Rochelle", department: "Charente-Maritime", departmentCode: "17", region: "Nouvelle-Aquitaine", population: 79000, postalCode: "17000", cpam: { name: "CPAM de la Charente-Maritime", phone: "36 46" }, hospitals: ["ch-la-rochelle"], nearbyCities: ["niort", "angouleme", "bordeaux"] },
  { slug: "angouleme", name: "Angoulême", department: "Charente", departmentCode: "16", region: "Nouvelle-Aquitaine", population: 42000, postalCode: "16000", cpam: { name: "CPAM de la Charente", phone: "36 46" }, hospitals: ["ch-angouleme"], nearbyCities: ["limoges", "poitiers", "bordeaux", "perigueux", "la-rochelle"] },
  { slug: "perigueux", name: "Périgueux", department: "Dordogne", departmentCode: "24", region: "Nouvelle-Aquitaine", population: 30000, postalCode: "24000", cpam: { name: "CPAM de la Dordogne", phone: "36 46" }, hospitals: ["ch-perigueux"], nearbyCities: ["bordeaux", "limoges", "angouleme", "agen"] },
  { slug: "agen", name: "Agen", department: "Lot-et-Garonne", departmentCode: "47", region: "Nouvelle-Aquitaine", population: 34000, postalCode: "47000", cpam: { name: "CPAM de Lot-et-Garonne", phone: "36 46" }, hospitals: ["ch-agen"], nearbyCities: ["bordeaux", "toulouse", "mont-de-marsan", "perigueux", "cahors"] },
  { slug: "mont-de-marsan", name: "Mont-de-Marsan", department: "Landes", departmentCode: "40", region: "Nouvelle-Aquitaine", population: 32000, postalCode: "40000", cpam: { name: "CPAM des Landes", phone: "36 46" }, hospitals: ["ch-mont-de-marsan"], nearbyCities: ["bordeaux", "pau", "agen"] },
  { slug: "pau", name: "Pau", department: "Pyrénées-Atlantiques", departmentCode: "64", region: "Nouvelle-Aquitaine", population: 77000, postalCode: "64000", cpam: { name: "CPAM des Pyrénées-Atlantiques", phone: "36 46" }, hospitals: ["ch-pau"], nearbyCities: ["mont-de-marsan", "tarbes", "bordeaux"] },
  { slug: "tulle", name: "Tulle", department: "Corrèze", departmentCode: "19", region: "Nouvelle-Aquitaine", population: 14000, postalCode: "19000", cpam: { name: "CPAM de la Corrèze", phone: "36 46" }, hospitals: ["ch-tulle"], nearbyCities: ["limoges", "clermont-ferrand", "aurillac", "cahors"] },
  { slug: "gueret", name: "Guéret", department: "Creuse", departmentCode: "23", region: "Nouvelle-Aquitaine", population: 13000, postalCode: "23000", cpam: { name: "CPAM de la Creuse", phone: "36 46" }, hospitals: ["ch-gueret"], nearbyCities: ["limoges", "moulins", "clermont-ferrand"] },

  // ─── Occitanie ───────────────────────────────────────────────
  { slug: "toulouse", name: "Toulouse", department: "Haute-Garonne", departmentCode: "31", region: "Occitanie", population: 498000, postalCode: "31000", cpam: { name: "CPAM de la Haute-Garonne", phone: "36 46" }, hospitals: ["chu-toulouse", "institut-claudius-regaud", "clinique-pasteur-toulouse"], nearbyCities: ["montauban", "auch", "tarbes", "foix", "carcassonne", "albi", "agen"] },
  { slug: "montpellier", name: "Montpellier", department: "Hérault", departmentCode: "34", region: "Occitanie", population: 295000, postalCode: "34000", cpam: { name: "CPAM de l'Hérault", phone: "36 46" }, hospitals: ["chu-montpellier", "icm-montpellier"], nearbyCities: ["nimes", "perpignan", "carcassonne", "beziers", "avignon"] },
  { slug: "nimes", name: "Nîmes", department: "Gard", departmentCode: "30", region: "Occitanie", population: 151000, postalCode: "30000", cpam: { name: "CPAM du Gard", phone: "36 46" }, hospitals: ["chu-nimes"], nearbyCities: ["montpellier", "avignon", "mende", "albi"] },
  { slug: "perpignan", name: "Perpignan", department: "Pyrénées-Orientales", departmentCode: "66", region: "Occitanie", population: 121000, postalCode: "66000", cpam: { name: "CPAM des Pyrénées-Orientales", phone: "36 46" }, hospitals: ["ch-perpignan"], nearbyCities: ["montpellier", "carcassonne", "foix"] },
  { slug: "carcassonne", name: "Carcassonne", department: "Aude", departmentCode: "11", region: "Occitanie", population: 47000, postalCode: "11000", cpam: { name: "CPAM de l'Aude", phone: "36 46" }, hospitals: ["ch-carcassonne"], nearbyCities: ["toulouse", "montpellier", "perpignan", "foix"] },
  { slug: "foix", name: "Foix", department: "Ariège", departmentCode: "09", region: "Occitanie", population: 10000, postalCode: "09000", cpam: { name: "CPAM de l'Ariège", phone: "36 46" }, hospitals: ["ch-ariege-couserans"], nearbyCities: ["toulouse", "carcassonne", "tarbes", "perpignan"] },
  { slug: "tarbes", name: "Tarbes", department: "Hautes-Pyrénées", departmentCode: "65", region: "Occitanie", population: 42000, postalCode: "65000", cpam: { name: "CPAM des Hautes-Pyrénées", phone: "36 46" }, hospitals: ["ch-tarbes"], nearbyCities: ["pau", "toulouse", "auch", "foix"] },
  { slug: "auch", name: "Auch", department: "Gers", departmentCode: "32", region: "Occitanie", population: 22000, postalCode: "32000", cpam: { name: "CPAM du Gers", phone: "36 46" }, hospitals: ["ch-auch"], nearbyCities: ["toulouse", "tarbes", "agen", "montauban"] },
  { slug: "montauban", name: "Montauban", department: "Tarn-et-Garonne", departmentCode: "82", region: "Occitanie", population: 61000, postalCode: "82000", cpam: { name: "CPAM de Tarn-et-Garonne", phone: "36 46" }, hospitals: ["ch-montauban"], nearbyCities: ["toulouse", "cahors", "agen", "albi", "auch"] },
  { slug: "albi", name: "Albi", department: "Tarn", departmentCode: "81", region: "Occitanie", population: 50000, postalCode: "81000", cpam: { name: "CPAM du Tarn", phone: "36 46" }, hospitals: ["ch-albi"], nearbyCities: ["toulouse", "montauban", "rodez", "castres"] },
  { slug: "rodez", name: "Rodez", department: "Aveyron", departmentCode: "12", region: "Occitanie", population: 24000, postalCode: "12000", cpam: { name: "CPAM de l'Aveyron", phone: "36 46" }, hospitals: ["ch-rodez"], nearbyCities: ["albi", "aurillac", "mende", "montpellier"] },
  { slug: "cahors", name: "Cahors", department: "Lot", departmentCode: "46", region: "Occitanie", population: 20000, postalCode: "46000", cpam: { name: "CPAM du Lot", phone: "36 46" }, hospitals: ["ch-cahors"], nearbyCities: ["montauban", "agen", "tulle", "rodez"] },
  { slug: "mende", name: "Mende", department: "Lozère", departmentCode: "48", region: "Occitanie", population: 12000, postalCode: "48000", cpam: { name: "CPAM de la Lozère", phone: "36 46" }, hospitals: ["ch-mende"], nearbyCities: ["rodez", "le-puy-en-velay", "nimes", "privas"] },

  // ─── Provence-Alpes-Côte d'Azur ──────────────────────────────
  { slug: "marseille", name: "Marseille", department: "Bouches-du-Rhône", departmentCode: "13", region: "Provence-Alpes-Côte d'Azur", population: 873000, postalCode: "13000", cpam: { name: "CPAM des Bouches-du-Rhône", phone: "36 46" }, hospitals: ["ap-hm", "institut-paoli-calmettes", "hopital-nord-marseille", "hopital-timone"], nearbyCities: ["aix-en-provence", "toulon", "avignon", "nice", "digne-les-bains", "gap"] },
  { slug: "nice", name: "Nice", department: "Alpes-Maritimes", departmentCode: "06", region: "Provence-Alpes-Côte d'Azur", population: 342000, postalCode: "06000", cpam: { name: "CPAM des Alpes-Maritimes", phone: "36 46" }, hospitals: ["chu-nice", "centre-antoine-lacassagne"], nearbyCities: ["marseille", "toulon", "digne-les-bains", "gap"] },
  { slug: "toulon", name: "Toulon", department: "Var", departmentCode: "83", region: "Provence-Alpes-Côte d'Azur", population: 176000, postalCode: "83000", cpam: { name: "CPAM du Var", phone: "36 46" }, hospitals: ["ch-toulon"], nearbyCities: ["marseille", "nice", "digne-les-bains"] },
  { slug: "avignon", name: "Avignon", department: "Vaucluse", departmentCode: "84", region: "Provence-Alpes-Côte d'Azur", population: 92000, postalCode: "84000", cpam: { name: "CPAM de Vaucluse", phone: "36 46" }, hospitals: ["ch-avignon"], nearbyCities: ["marseille", "nimes", "montpellier", "valence"] },
  { slug: "digne-les-bains", name: "Digne-les-Bains", department: "Alpes-de-Haute-Provence", departmentCode: "04", region: "Provence-Alpes-Côte d'Azur", population: 17000, postalCode: "04000", cpam: { name: "CPAM des Alpes-de-Haute-Provence", phone: "36 46" }, hospitals: ["ch-digne"], nearbyCities: ["gap", "nice", "marseille", "toulon"] },
  { slug: "gap", name: "Gap", department: "Hautes-Alpes", departmentCode: "05", region: "Provence-Alpes-Côte d'Azur", population: 41000, postalCode: "05000", cpam: { name: "CPAM des Hautes-Alpes", phone: "36 46" }, hospitals: ["ch-gap"], nearbyCities: ["grenoble", "digne-les-bains", "nice"] },

  // ─── Bretagne ────────────────────────────────────────────────
  { slug: "rennes", name: "Rennes", department: "Ille-et-Vilaine", departmentCode: "35", region: "Bretagne", population: 222000, postalCode: "35000", cpam: { name: "CPAM d'Ille-et-Vilaine", phone: "36 46" }, hospitals: ["chu-rennes", "centre-eugene-marquis"], nearbyCities: ["saint-brieuc", "vannes", "nantes", "laval"] },
  { slug: "saint-brieuc", name: "Saint-Brieuc", department: "Côtes-d'Armor", departmentCode: "22", region: "Bretagne", population: 45000, postalCode: "22000", cpam: { name: "CPAM des Côtes-d'Armor", phone: "36 46" }, hospitals: ["ch-saint-brieuc"], nearbyCities: ["rennes", "brest", "quimper", "vannes"] },
  { slug: "brest", name: "Brest", department: "Finistère", departmentCode: "29", region: "Bretagne", population: 142000, postalCode: "29200", cpam: { name: "CPAM du Finistère", phone: "36 46" }, hospitals: ["chru-brest"], nearbyCities: ["quimper", "saint-brieuc", "rennes"] },
  { slug: "quimper", name: "Quimper", department: "Finistère", departmentCode: "29", region: "Bretagne", population: 63000, postalCode: "29000", cpam: { name: "CPAM du Finistère", phone: "36 46" }, hospitals: ["ch-quimper"], nearbyCities: ["brest", "vannes", "saint-brieuc"] },
  { slug: "vannes", name: "Vannes", department: "Morbihan", departmentCode: "56", region: "Bretagne", population: 53000, postalCode: "56000", cpam: { name: "CPAM du Morbihan", phone: "36 46" }, hospitals: ["ch-bretagne-atlantique"], nearbyCities: ["rennes", "quimper", "nantes", "saint-brieuc"] },

  // ─── Pays de la Loire ────────────────────────────────────────
  { slug: "nantes", name: "Nantes", department: "Loire-Atlantique", departmentCode: "44", region: "Pays de la Loire", population: 320000, postalCode: "44000", cpam: { name: "CPAM de Loire-Atlantique", phone: "36 46" }, hospitals: ["chu-nantes", "icm-nantes"], nearbyCities: ["rennes", "vannes", "angers", "la-roche-sur-yon", "la-rochelle"] },
  { slug: "angers", name: "Angers", department: "Maine-et-Loire", departmentCode: "49", region: "Pays de la Loire", population: 155000, postalCode: "49000", cpam: { name: "CPAM de Maine-et-Loire", phone: "36 46" }, hospitals: ["chu-angers", "icm-angers"], nearbyCities: ["nantes", "le-mans", "tours", "laval"] },
  { slug: "le-mans", name: "Le Mans", department: "Sarthe", departmentCode: "72", region: "Pays de la Loire", population: 145000, postalCode: "72000", cpam: { name: "CPAM de la Sarthe", phone: "36 46" }, hospitals: ["ch-le-mans"], nearbyCities: ["angers", "tours", "laval", "chartres"] },
  { slug: "laval", name: "Laval", department: "Mayenne", departmentCode: "53", region: "Pays de la Loire", population: 53000, postalCode: "53000", cpam: { name: "CPAM de la Mayenne", phone: "36 46" }, hospitals: ["ch-laval"], nearbyCities: ["le-mans", "rennes", "angers"] },
  { slug: "la-roche-sur-yon", name: "La Roche-sur-Yon", department: "Vendée", departmentCode: "85", region: "Pays de la Loire", population: 55000, postalCode: "85000", cpam: { name: "CPAM de la Vendée", phone: "36 46" }, hospitals: ["ch-la-roche-sur-yon"], nearbyCities: ["nantes", "niort", "la-rochelle"] },

  // ─── Normandie ───────────────────────────────────────────────
  { slug: "rouen", name: "Rouen", department: "Seine-Maritime", departmentCode: "76", region: "Normandie", population: 113000, postalCode: "76000", cpam: { name: "CPAM de Seine-Maritime", phone: "36 46" }, hospitals: ["chu-rouen", "centre-henri-becquerel"], nearbyCities: ["le-havre", "evreux", "beauvais", "amiens", "caen"] },
  { slug: "caen", name: "Caen", department: "Calvados", departmentCode: "14", region: "Normandie", population: 106000, postalCode: "14000", cpam: { name: "CPAM du Calvados", phone: "36 46" }, hospitals: ["chu-caen", "centre-francois-baclesse"], nearbyCities: ["rouen", "saint-lo", "alencon", "evreux"] },
  { slug: "evreux", name: "Évreux", department: "Eure", departmentCode: "27", region: "Normandie", population: 50000, postalCode: "27000", cpam: { name: "CPAM de l'Eure", phone: "36 46" }, hospitals: ["ch-evreux"], nearbyCities: ["rouen", "caen", "chartres", "versailles"] },
  { slug: "alencon", name: "Alençon", department: "Orne", departmentCode: "61", region: "Normandie", population: 26000, postalCode: "61000", cpam: { name: "CPAM de l'Orne", phone: "36 46" }, hospitals: ["ch-alencon"], nearbyCities: ["caen", "le-mans", "laval"] },
  { slug: "saint-lo", name: "Saint-Lô", department: "Manche", departmentCode: "50", region: "Normandie", population: 19000, postalCode: "50000", cpam: { name: "CPAM de la Manche", phone: "36 46" }, hospitals: ["ch-saint-lo"], nearbyCities: ["caen", "rennes"] },

  // ─── Centre-Val de Loire ─────────────────────────────────────
  { slug: "orleans", name: "Orléans", department: "Loiret", departmentCode: "45", region: "Centre-Val de Loire", population: 116000, postalCode: "45000", cpam: { name: "CPAM du Loiret", phone: "36 46" }, hospitals: ["chr-orleans"], nearbyCities: ["tours", "chartres", "bourges", "auxerre", "blois"] },
  { slug: "tours", name: "Tours", department: "Indre-et-Loire", departmentCode: "37", region: "Centre-Val de Loire", population: 137000, postalCode: "37000", cpam: { name: "CPAM d'Indre-et-Loire", phone: "36 46" }, hospitals: ["chru-tours"], nearbyCities: ["orleans", "blois", "poitiers", "le-mans", "angers", "bourges", "chateauroux"] },
  { slug: "chartres", name: "Chartres", department: "Eure-et-Loir", departmentCode: "28", region: "Centre-Val de Loire", population: 39000, postalCode: "28000", cpam: { name: "CPAM d'Eure-et-Loir", phone: "36 46" }, hospitals: ["ch-chartres"], nearbyCities: ["orleans", "evreux", "versailles", "le-mans"] },
  { slug: "blois", name: "Blois", department: "Loir-et-Cher", departmentCode: "41", region: "Centre-Val de Loire", population: 46000, postalCode: "41000", cpam: { name: "CPAM de Loir-et-Cher", phone: "36 46" }, hospitals: ["ch-blois"], nearbyCities: ["tours", "orleans", "bourges"] },
  { slug: "bourges", name: "Bourges", department: "Cher", departmentCode: "18", region: "Centre-Val de Loire", population: 65000, postalCode: "18000", cpam: { name: "CPAM du Cher", phone: "36 46" }, hospitals: ["ch-bourges"], nearbyCities: ["orleans", "nevers", "moulins", "chateauroux", "tours"] },
  { slug: "chateauroux", name: "Châteauroux", department: "Indre", departmentCode: "36", region: "Centre-Val de Loire", population: 43000, postalCode: "36000", cpam: { name: "CPAM de l'Indre", phone: "36 46" }, hospitals: ["ch-chateauroux"], nearbyCities: ["tours", "bourges", "limoges", "poitiers"] },

  // ─── Bourgogne-Franche-Comté ─────────────────────────────────
  { slug: "dijon", name: "Dijon", department: "Côte-d'Or", departmentCode: "21", region: "Bourgogne-Franche-Comté", population: 159000, postalCode: "21000", cpam: { name: "CPAM de la Côte-d'Or", phone: "36 46" }, hospitals: ["chu-dijon", "centre-gf-leclerc"], nearbyCities: ["besancon", "macon", "auxerre", "nevers", "chaumont"] },
  { slug: "besancon", name: "Besançon", department: "Doubs", departmentCode: "25", region: "Bourgogne-Franche-Comté", population: 119000, postalCode: "25000", cpam: { name: "CPAM du Doubs", phone: "36 46" }, hospitals: ["chru-besancon"], nearbyCities: ["dijon", "colmar", "epinal", "lons-le-saunier", "vesoul"] },
  { slug: "auxerre", name: "Auxerre", department: "Yonne", departmentCode: "89", region: "Bourgogne-Franche-Comté", population: 35000, postalCode: "89000", cpam: { name: "CPAM de l'Yonne", phone: "36 46" }, hospitals: ["ch-auxerre"], nearbyCities: ["dijon", "troyes", "orleans", "nevers", "melun"] },
  { slug: "nevers", name: "Nevers", department: "Nièvre", departmentCode: "58", region: "Bourgogne-Franche-Comté", population: 33000, postalCode: "58000", cpam: { name: "CPAM de la Nièvre", phone: "36 46" }, hospitals: ["ch-nevers"], nearbyCities: ["bourges", "moulins", "dijon", "auxerre"] },
  { slug: "macon", name: "Mâcon", department: "Saône-et-Loire", departmentCode: "71", region: "Bourgogne-Franche-Comté", population: 34000, postalCode: "71000", cpam: { name: "CPAM de Saône-et-Loire", phone: "36 46" }, hospitals: ["ch-macon"], nearbyCities: ["lyon", "dijon", "bourg-en-bresse"] },
  { slug: "lons-le-saunier", name: "Lons-le-Saunier", department: "Jura", departmentCode: "39", region: "Bourgogne-Franche-Comté", population: 17000, postalCode: "39000", cpam: { name: "CPAM du Jura", phone: "36 46" }, hospitals: ["ch-lons-le-saunier"], nearbyCities: ["besancon", "dijon", "macon", "bourg-en-bresse"] },
  { slug: "vesoul", name: "Vesoul", department: "Haute-Saône", departmentCode: "70", region: "Bourgogne-Franche-Comté", population: 15000, postalCode: "70000", cpam: { name: "CPAM de la Haute-Saône", phone: "36 46" }, hospitals: ["ch-vesoul"], nearbyCities: ["besancon", "epinal", "colmar"] },
  { slug: "belfort", name: "Belfort", department: "Territoire de Belfort", departmentCode: "90", region: "Bourgogne-Franche-Comté", population: 46000, postalCode: "90000", cpam: { name: "CPAM du Territoire de Belfort", phone: "36 46" }, hospitals: ["ch-belfort-montbeliard"], nearbyCities: ["besancon", "colmar", "epinal"] },

  // ─── Corse ───────────────────────────────────────────────────
  { slug: "ajaccio", name: "Ajaccio", department: "Corse-du-Sud", departmentCode: "2A", region: "Corse", population: 72000, postalCode: "20000", cpam: { name: "CPAM de Corse-du-Sud", phone: "36 46" }, hospitals: ["ch-ajaccio"], nearbyCities: ["bastia"] },
  { slug: "bastia", name: "Bastia", department: "Haute-Corse", departmentCode: "2B", region: "Corse", population: 48000, postalCode: "20200", cpam: { name: "CPAM de Haute-Corse", phone: "36 46" }, hospitals: ["ch-bastia"], nearbyCities: ["ajaccio"] },

  // ─── Outre-Mer ───────────────────────────────────────────────
  { slug: "fort-de-france", name: "Fort-de-France", department: "Martinique", departmentCode: "972", region: "Martinique", population: 76000, postalCode: "97200", cpam: { name: "CGSS de la Martinique", phone: "36 46" }, hospitals: ["chu-martinique"], nearbyCities: [] },
  { slug: "pointe-a-pitre", name: "Pointe-à-Pitre", department: "Guadeloupe", departmentCode: "971", region: "Guadeloupe", population: 15000, postalCode: "97110", cpam: { name: "CGSS de la Guadeloupe", phone: "36 46" }, hospitals: ["chu-guadeloupe"], nearbyCities: [] },
  { slug: "cayenne", name: "Cayenne", department: "Guyane", departmentCode: "973", region: "Guyane", population: 63000, postalCode: "97300", cpam: { name: "CGSS de la Guyane", phone: "36 46" }, hospitals: ["ch-cayenne"], nearbyCities: [] },
  { slug: "saint-denis-reunion", name: "Saint-Denis", department: "La Réunion", departmentCode: "974", region: "La Réunion", population: 153000, postalCode: "97400", cpam: { name: "CGSS de La Réunion", phone: "36 46" }, hospitals: ["chu-reunion"], nearbyCities: [] },
  { slug: "mamoudzou", name: "Mamoudzou", department: "Mayotte", departmentCode: "976", region: "Mayotte", population: 71000, postalCode: "97600", cpam: { name: "CSSM de Mayotte", phone: "36 46" }, hospitals: ["ch-mayotte"], nearbyCities: [] },
];
